<AutoPilot:project xmlns:AutoPilot="com.autoesl.autopilot.project" top="v_frmbuf_rd" name="prj">
    <includePaths/>
    <libraryFlag/>
    <solutions>
        <solution name="sol" status=""/>
    </solutions>
    <files>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_undistort.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_types.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_stereobm.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_mem.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_io.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_imgproc.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_imgbase.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_hough.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_histogram.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_harris.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_haar.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_fast.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_core.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_video_arithm.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls/hls_axi_io.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls_opencv.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls_video.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/v_frmbuf_rd.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/v_frmbuf_rd.cpp" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
        <file name="/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/v_frmbuf_rd_config.h" sc="0" tb="false" cflags="-I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src/hls -I/home/zacharie/FPGA_Projects/fpga-image-processing/FPGA/Vivado/CameraPipeline.gen/sources_1/bd/top/ip/top_v_frmbuf_rd_0_0_1/src" csimflags="" blackbox="false"/>
    </files>
</AutoPilot:project>

