
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xundistort_coordinate_generator.h"

/*
* The configuration table for devices
*/

XUndistort_coordinate_generator_Config XUndistort_coordinate_generator_ConfigTable[XPAR_XUNDISTORT_COORDINATE_GENERATOR_NUM_INSTANCES] =
{
	{
		XPAR_UNDISTORT_COORDINATE_0_DEVICE_ID,
		XPAR_UNDISTORT_COORDINATE_0_S_AXI_CONTROL_BASEADDR
	}
};


